---
name: AWS Glue and Terraform Setup

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Si usas MFA o sesiones temporales
        aws-region: us-east-1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Python and Boto3
      run: |
        sudo apt-get install -y python3 python3-pip
        pip3 install boto3

    - name: Terraform Initialization
      run: |
        terraform init

    - name: Apply Terraform Configuration
      run: |
        terraform apply --auto-approve

    - name: Run Python Script to interact with S3
      run: |
        python3 ./estas3bucket.py

    - name: Start Glue Crawler
      run: |
        aws glue start-crawler --name netuptinteligencianegocios-crawler

    - name: Wait for Glue Table Creation
      run: |
        while true; do
          status=$(aws glue get-table --database-name tb_redupt_database --name netuptinteligencianegocios --query 'Table.UpdateTime' --output text)
          if [ "$status" != "None" ]; then
            echo "Glue Table has been created successfully."
            break
          fi
          echo "Waiting for Glue Table creation..."
          sleep 30
        done
